import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { Container, Flex } from "@chakra-ui/react";

const Home: NextPage = () => {
  const { data } = api.posts.getAll.useQuery();
  console.log(data)
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.2xl" h="100%" bg="green">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        <Flex>
          {data?.map((post) => (
            <div key={post.id}>
              {post.content}
            </div>
          ))}
        </Flex>
      </Container>
    </>
  );
};

export default Home;
